config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :adoption_centers
  resources :users 
  resources :cats, only: [:index, :new, :create, :edit, :update]

  get '/', to: 'application#welcome', as: "home"
  get '/transition', to: 'flow#transition', as: "flow"
  get '/success', to: 'flow#success', as: "success"
  get '/sessions/new', to: 'sessions#new', as: "new_login"
  post '/sessions', to: 'sessions#create', as: "login"
  get "signup", to: "users#new", as: "signup"
  delete "/sessions/logout", to: "sessions#logout", as: "logout"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adoption_center.rb
class AdoptionCenter < ApplicationRecord
    has_many :listings
    has_many :cats, through: :listings
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
    has_many :listings
    has_many :adoption_centers, through: :listings

    validates :name, presence: true
    validates :breed, presence: true
    validates :age, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
    belongs_to :adoption_center
    belongs_to :cat

    validates :title, presence: true
    validates :content, presence: true
    validates :date_added, presence: true
    validates :cat_id, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, uniqueness: :true
    
    has_secure_password
end

app/controllers/adoption_centers_controller.rb
class AdoptionCentersController < ApplicationController

    def index
        @adoption_centers = AdoptionCenter.all
    end

    def show
        @adoption_center = AdoptionCenter.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :logged_in?
  
  def welcome
  end

  def current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end

end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
    end

    def new
        @cat = Cat.new
    end

    def create
        @cat = Cat.create(cat_params)
        if @cat.valid?
            redirect_to new_listing_path
        else
            flash[:errors] = @cat.errors.full_messages
            redirect_to new_cat_path
        end  
    end

    private

    def cat_params
        params.require(:cat).permit!
    end

end

app/controllers/flow_controller.rb
class FlowController < ApplicationController

    def transition
        if logged_in?
            render :transition
        else
            flash[:mob] = "You need to be logged in as an employee!"
            redirect_to listings_path
        end
    end
    
    def success
    end 
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
    before_action :find_listing, only: [:show, :edit, :update, :destroy]
    before_action :logged_in?

    def index
        @listings = Listing.all 
    end

    def show
        @cat = @listing.cat
    end

    def new
      @listing = Listing.new
      @cats = Cat.all
      @adoption_centers = AdoptionCenter.all
    end

    def create
        @listing = Listing.create(listings_params)

        if @listing.valid?
            redirect_to listing_path(@listing)
        else 
            flash[:errors] = @listing.errors.full_messages
            redirect_to new_listing_path
        end
    end

    def edit
        if logged_in?
            @cats = Cat.all
            @adoption_centers = AdoptionCenter.all
            render :edit
        else
            flash[:mob] = "You need to be logged in as an employee!"
            redirect_to listing_path(@listing)
        end
    end

    def update
        @listing.update(listings_params)
        redirect_to listing_path(@listing)
    end

    def destroy
        @listing.destroy
        redirect_to listings_path
    end


    private

    def find_listing
        @listing = Listing.find(params[:id])
    end

    def listings_params
        params.require(:listing).permit!
    end 
    
end 
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end


  def create 
    @user = User.find_by(username: params[:session][:username])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      redirect_to listings_path
    else
      flash[:error] = "Username or Password is Incorrect"
      redirect_to new_login_path
    end  

  end 

  def logout
    session.delete(:user_id)
    redirect_to home_path
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end
    
    def create
      user = User.create(user_params)
  
      if user.valid? 
        session[:user_id] = user.id
        flash[:success] = "You've successfully Signed Up!"
        redirect_to listings_path
      else
        flash[:errors] = user.errors.full_messages

        redirect_to new_user_path 
      end 
    end
    
  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/adoption_centers_helper.rb
module AdoptionCentersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adoption_centers/index.html.erb
<h1>View All Adoption Centers</h1>

<div class="flex-container">
  <% @adoption_centers.each do |adoption_center| %>
    <div class="card"> Center Name: <%= adoption_center.name %>    
      Location: <%= adoption_center.location %><br>
      <%= link_to "Contact Here", adoption_center_path(adoption_center) %>
    </div>
  <% end %>
</div>

  
    
  
   

app/views/adoption_centers/show.html.erb
<h1>Contact Us!</h1>

<p> Center Name: <%= @adoption_center.name %></p>
<p>Center Location: <%= @adoption_center.location %></p>

<form action="<%= success_path %>" method="GET">
    <label>Email Address:</label><br>
    <input type="text" id="post_title" name="post[title]"><br>
    <label>Inquiry:</label><br>
    <textarea id="post_description" name="post[description]"></textarea><br>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="Send Inquiry">
</form>

app/views/application/welcome.html.erb
 <!-- <link rel="stylesheet" href= "./welcome.scss"/> -->
<h1 class="banner">Welcome to PurrEver Home!</h1>



<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.scotsman.com%2Fimages-i.jpimedia.uk%2Fimagefetch%2Fhttps%3A%2F%2Fjpgreatcontent.co.uk%2Fwp-content%2Fuploads%2F2020%2F04%2Fcarole-baskin.jpg&f=1&nofb=1" alt="Carol Baskin leaning next to a tiger.">

app/views/cats/new.html.erb
<h1>Create a New Cat!</h1>

<%= render 'listings/flash' %>

<%= form_for @cat do |f| %>
<%= f.label :name %>
<%= f.text_field :name%><br>

<%= f.label :breed %>
<%= f.text_field :breed%><br>

<%= f.label :age %>
<%= f.number_field :age%><br>

<%= f.label :image_url %>
<%= f.text_field :image_url%><br>

<%= f.label :favorite_food %>
<%= f.text_field :favorite_food %><br>

<%= f.submit%>

<%end%>

app/views/flow/success.html.erb
<h1>Success!</h1>

<h3>Your message was successfully submitted!</h3>

<%= button_to "Welcome Page", home_path, method: :get %>

app/views/flow/transition.html.erb
<h1>Hey all you cool cats and kittens!!</h1>

<h3> All of our lovely purr babies are already listed! Since we never have a spare cat without a listing, you'll need to create a new cat per new listing.</h3>

<%= button_to "Create a Cat!", new_cat_path, method: :get%>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <title>PurrEverHome</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href= "./application.css"/>
    <link rel="stylesheet" href= "./welcome.scss"/>
    <link rel="stylesheet" href= "./welcome.scss"/>
    <link rel="stylesheet" href= "./adoption_centers.scss"/>
  </head>

  <body>
    <div id="navbar"> 
      <ul>
        <li><%= link_to 'All Listings', listings_path %></li>
        <li><%= link_to "Create a New Listing!", flow_path %></li>
        <li><%= link_to 'All Adoption Centers', adoption_centers_path %></li>

        <% if @current_user %>
          <li class='right'> Welcome <%=  @current_user.username %></li>                    
          <li class='right'><%= link_to "Log-Out", logout_path, method: :delete %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
          <li class='right'><%= link_to 'Login', new_login_path %></li>
        <% end %>
      </ul>
    </div> 
  <%= yield %>
  </body>
</html>

app/views/listings/_flash.html.erb
<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <p> <%= error %> </p>
    <% end %>
<% end %>

app/views/listings/edit.html.erb
<%= render 'flash' %>

<%= form_for @listing do |f| %>
<%= f.label :title %>
<%= f.text_field :title %> <br>

<%= f.label :content %>
<%= f.text_field :content %><br>

<%= f.label:date_added %>
<%= f.date_field :date_added %><br>

<%= f.label:adoption_center_id %>
<%= f.collection_select :adoption_center_id, @adoption_centers, :id, :location %><br>

<%= f.submit %>

<% end %>

<%= button_to "Delete Listing", listing_path(@listing), method: :delete%>

app/views/listings/index.html.erb
<h1>All Listings</h1>
<% if flash[:success] %>
  <h3><%= flash[:success] %></h3>
<%end%>

<% if flash[:mob] %>
  <h3><%= flash[:mob] %></h3>
<%end%>

<div class="flex-container">
  <% @listings.each do |listing| %>
    <div class="card"><%=link_to listing.cat.name, listing_path(listing) %>
      <a href="<%=listing_path(listing)%>"><img src="<%= listing.cat.image_url%>">
    </div>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>Create New Listing!</h1>

<h3>Now that the new kitty is created, make your listing!</h3>

<%= render 'flash' %>

<%= form_for @listing do |f| %>
<%= f.label :title %>
<%= f.text_field :title %> <br>

<%= f.label :content %>
<%= f.text_field :content %><br>

<%= f.label:date_added %>
<%= f.date_field :date_added %><br>

<%= f.label:cat_id %>
<%= f.collection_select :cat_id, @cats, :id, :name %><br>

<%= f.label:adoption_center_id %>
<%= f.collection_select :adoption_center_id, @adoption_centers, :id, :location %><br>

<%= f.submit %>

<% end %>

app/views/listings/show.html.erb
<h1><%= @cat.name %>'s Listing </h1>

<%if flash[:mob] %>
    <h3><%= flash[:mob] %></h3>
<% end %>

<h4>Adoption Center: <%= @listing.adoption_center.location %></h4>
<h4>Posted On: <%= @listing.date_added.strftime("%m-%d-%Y") %></h3><br>

<%= image_tag "#{@cat.image_url}" %><br>

<h3>Name: <%= @cat.name %></h3>
<h3>Breed: <%= @cat.breed %></h3>
<h3>Age: <%= @cat.age %></h3>
<h3><%=@cat.name%>'s Content: <%= @listing.content %></h3>
<h3>Favorite Title: <%= @listing.title %></h3>
<h3>Favorite Food: <%= @cat.favorite_food%></h3>

<p><%= button_to "Edit Listing", edit_listing_path, method: :get %></p>

app/views/users/new.html.erb
<%= render 'listings/flash' %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>
<% end %>